[theme]
base = "light"
# Primary accent for interactive elements
primaryColor = '#FD349C'

# Background color for the main content area
backgroundColor = '#00338D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1E49E2'

# Color used for almost all text
textColor = '#ACEAFF'
